# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20190610_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(max_length=15),
        ),
    ]
